name: Ejecutar Colab cada hora

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora
  workflow_dispatch:     # También permite ejecutarlo manualmente

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert gspread gspread_dataframe pandas google-auth-oauthlib

      - name: Ejecutar notebook
        run: |
          jupyter nbconvert --to notebook --execute Reporte_de_internas.ipynb --output ejecutado.ipynb
